name: Sonare
description: "Avec Sonare, naviguez sous les radars."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  http: ^1.2.0
  shimmer: ^3.0.0
  audioplayers: ^6.1.0
  flutter_compass: ^0.8.0
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^18.0.1

# Edit here to change the splash screen
# Then run : flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#000000"
  image: assets/logo/icon.png
  android: true
  ios: true

# Edit here to change the app logo
# Logo must be 512px * 512px
# Then run : flutter pub run flutter_launcher_icons:main 
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/icon_and_background.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Public_Sans
      fonts:
        - asset: fonts/Public_Sans/static/PublicSans-Regular.ttf
        - asset: fonts/Public_Sans/static/PublicSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/Public_Sans/static/PublicSans-Thin.ttf
          weight: 200
        - asset: fonts/Public_Sans/static/PublicSans-ExtraBold.ttf
          weight: 900
        - asset: fonts/Public_Sans/static/PublicSans-ExtraBold.ttf
          weight: 900