name: Sonare
description: "L'application pour naviguer sous les radars."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  http: ^1.2.0
  shimmer: ^3.0.0
  flutter_compass: ^0.8.0
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.4
  flutter_vibrate: ^1.3.0
  audioplayers: ^6.1.0
  webview_flutter: ^4.10.0

# Edit here to change the splash screen
# Then run : flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#000000"
  image: assets/images/logo/icon.png
  android: true
  ios: true

# Edit here to change the app logo
# Logo must be 512px * 512px
# Then run : flutter pub run flutter_launcher_icons:main 
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/icon_and_background.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/logo/
    - assets/sounds/
  fonts:
    - family: sf-pro-display-ultralight
      fonts:
        - asset: assets/fonts/sf-pro-display/sf-pro-display-ultralight.otf
    - family: sf-pro-display-light
      fonts:
        - asset: assets/fonts/sf-pro-display/sf-pro-display-light.otf
    - family: sf-pro-display-regular
      fonts:
        - asset: assets/fonts/sf-pro-display/sf-pro-display-regular.otf
    - family: sf-pro-display-medium
      fonts:
        - asset: assets/fonts/sf-pro-display/sf-pro-display-medium.otf
    - family: sf-pro-display-semibold
      fonts:
        - asset: assets/fonts/sf-pro-display/sf-pro-display-semibold.otf
    - family: sf-pro-display-bold
      fonts:
        - asset: assets/fonts/sf-pro-display/sf-pro-display-bold.otf
    - family: sf-pro-display-heavy
      fonts:
        - asset: assets/fonts/sf-pro-display/sf-pro-display-heavy.otf
    - family: sf-pro-display-black
      fonts:
        - asset: assets/fonts/sf-pro-display/sf-pro-display-black.otf
        