services:
  db:
    platform: linux/amd64 # @TODO : comment this if you are on Windows
    image: postgis/postgis:latest
    container_name: postgis
    restart: always
    environment:
      POSTGRES_DB: sonare
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sonare
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgis_data: